version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.13.0

    working_directory: ~/circle-ci-react-pizza

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: restore node modules
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run lint
      - run:
          name: lint code
          command: npm run lint

      - run:
          name: build project
          command: npm run build
  
  deploy:
    docker:
      - image: cimg/node:16.13.0
        auth:
          username: daiteromu
          password: $DOCKERHUB_PASSWORD
    
    working_directory: ~/circle-ci-react-pizza

    steps:
      - checkout

      - run:
          name: deploy into AWS EC2
          command: sh ./.circleci/aws_server_deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          
          filters:
            branches:
              only:
                - main
