export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_SORT_BY = 'SET_SORT_BY';
export const SET_ORDER = 'SET_ORDER';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CATEGORIES_LOADED = 'SET_CATEGORIES_LOADED';

export const SET_PIZZAS = 'SET_PIZZAS';
export const SET_PIZZAS_LOADED = 'SET_PIZZAS_LOADED';

export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT';

export const ADD_PIZZA_TO_CART = 'ADD_PIZZA_TO_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const ADD_PIZZA_IN_CART_ITEM = 'ADD_PIZZA_IN_CART_ITEM';
export const REMOVE_PIZZA_IN_CART_ITEM = 'REMOVE_PIZZA_IN_CART_ITEM';
